config/routes.rb
    Rails.application.routes.draw do
      get 'pages/home'

      devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout'}
      root 'pages#home'
      resources :comments
      resources :scribes do
        member { post :vote }
      end
      match 'users/:permalink' => 'users#show', via: :get, as: :user_show
      match 'users/:permalink/logs' => 'users#logs', via: :get, as: :user_logs

      match 'create' => 'scribes#new', via: :get
      match 'admin' => 'pages#admin', via: :get

      # Post Show
      get 'tags/:tag', to: 'scribes#index', as: :tag
    end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true
  validates :username, length: {
    minimum: 2,
    maximum: 30,
    too_short: "must have at least %{count} words",
    too_long: "must have at most %{count} words"
  }
  validates :username, format: { with: /^[0-9a-zA-Z]*$/, :multiline => true,
    message: "fewf" }

  has_many :scribes
  has_many :comments

  before_save :set_permalink

  has_reputation :votes, source: {reputation: :votes, of: :scribes}, aggregated_by: :sum

  def to_param
    self.permalink
  end

  def url
    "/users/#{self.permalink}"
  end

  private
  def set_permalink
    self.permalink = self.username.downcase
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by!(permalink: params[:permalink])
  end

  def logs
    @user = User.find_by!(permalink: params[:permalink])
    @scribes = @user.scribes.all.order("created_at DESC").page(params[:page]).per(6)  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/logs.html.erb
<header class="profile-page-header">
  <div class="width">
    <div class="profile-avatar">
      <%= image_tag avatar_url(@user) %>
    </div>
    <div class="profile-header-text">
      <h2><%= @user.username %></h2>
    </div>
    <% unless !user_signed_in? %>
      <% if current_user.id == @user.id || current_user.admin %>
        <%= link_to 'Edit Profile', edit_user_registration_path(@user), :class => 'edit-profile-button button' %>
      <% end %>
    <% end %>
  </div>
</header>

<div class="main">
  <div class="width">
    <div class="scribe-index-page cf">
      <% @scribes.each do |scribe| %>
        <div class="scribe-index">
          <%= link_to image_tag(scribe.video_image), scribe_path(scribe) %>
          <div class="index-text">
            <h3><%= link_to scribe.title, scribe_path(scribe) %></h3>
            <p><span>Logged by:</span> <%= link_to scribe.user.username, user_show_path(scribe.user) %></p>
          </div>
        </div>
        <div class="row-fix"></div>
      <% end %>
    </div>

    <%= paginate @scribes %>

  </div>
</div>

app/views/users/show.html.erb
<header class="profile-page-header">
  <div class="width">
    <div class="profile-avatar">
      <%= image_tag avatar_url(@user) %>
    </div>
    <div class="profile-header-text">
      <h2><%= @user.username %></h2>
    </div>
    <% unless !user_signed_in? %>
      <% if current_user.id == @user.id || current_user.admin %>
        <%= link_to 'Edit Profile', edit_user_registration_path(@user), :class => 'edit-profile-button button' %>
      <% end %>
    <% end %>
  </div>
</header>

<div class="main">
  <div class="width cf">

  <div class="profile-left">
  <h3>Bio</h3>
  <p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>
  </div>

  <div class="profile-right">
    <div class="cf">
      <% @user.scribes.last(6).each do |scribe| %>
        <div class="scribe-index2">
          <%= link_to image_tag(scribe.video_image), scribe_path(scribe) %>
          <h3><%= link_to scribe.title, scribe_path(scribe) %></h3>
          <% if current_user.id == @user.id || current_user.admin %>
            <%= link_to 'Edit', edit_scribe_path(scribe) %>
          <% end %>
        </div>
        <div class="row-fix2"></div>
      <% end %>
    </div>
      <%= link_to 'More', user_logs_path(@user), :class => "button rounded" %>
  </div>




  </div>
</div>