config/routes.rb
    Rails.application.routes.draw do
      get 'pages/home'

      devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout'}
      root 'pages#home'
      resources :comments
      resources :scribes do
        member { post :vote }
      end
      match 'users/:permalink' => 'users#show', via: :get, as: :user_show
      match 'users/:permalink/logs' => 'users#logs', via: :get, as: :user_logs

      match 'create' => 'scribes#new', via: :get
      match 'admin' => 'pages#admin', via: :get

      # Post Show
      get 'tags/:tag', to: 'scribes#index', as: :tag
    end

app/views/layouts/_footer.html.erb
<footer class="master-footer">
  <div class="width">

    <div class="footer-top">

      <div class="footer-box">
        <h3>Navigate</h3>
        <ul class="footer-nav">
          <li><%= link_to 'Home', scribes_path %></li>
          <li><%= link_to 'Create', new_scribe_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to 'Profile', user_show_path(current_user) %></li>
            <li><%= link_to 'logout', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %>

        </ul>
      </div>

      <div class="footer-box">
        <h3>Social</h3>
        <ul class="footer-nav">
          <li><a href="#">Facebook</a></li>
          <li><a href="#">Twitter</a></li>
        </ul>
      </div>

      <div class="footer-box long">
        <h3>Random Logs</h3>
        <ul class="footer-nav">
        <% random_logs.each do |randomz| %> 
          <li><%= link_to randomz.title, scribe_path(randomz) %></li>
        <% end %>
        </ul>
      </div>
    </div>

    <div class="footer-bottom">
      <p>&copy;2015 ytlogs.com</p>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScribedIo</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Oxygen:300,400,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
  <%= render 'layouts/header' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>  
  <% unless current_page?('/') %>
  <%= render 'layouts/footer' %>
  <% end %>
</body>
</html>